-- game532 ranking schema.
-- Run this once in the Supabase SQL editor (Dashboard -> SQL Editor -> New query).

create table if not exists public.scores (
  id          bigint generated by default as identity primary key,
  game_id     text not null,
  nickname    text not null,
  score       integer not null,
  created_at  timestamptz not null default now(),

  -- Defense in depth: the API route validates all of this too, but the database
  -- is the last line that cannot be bypassed by a bug in application code.
  constraint scores_game_id_valid check (game_id in ('dodge', 'poop', 'direction', 'stack', 'runner', 'aim')),
  constraint scores_nickname_len check (char_length(nickname) between 1 and 12),
  constraint scores_score_range check (score >= 0 and score <= 10000000)
);

-- Matches the ranking query exactly: filter by game, order by score desc then
-- created_at asc so the earliest submission wins a tie.
create index if not exists scores_ranking_idx
  on public.scores (game_id, score desc, created_at asc);

alter table public.scores enable row level security;

-- Rankings are public.
drop policy if exists "scores are publicly readable" on public.scores;
create policy "scores are publicly readable"
  on public.scores
  for select
  to anon, authenticated
  using (true);

-- No insert/update/delete policy exists on purpose.
-- Clients therefore cannot write at all; POST /api/scores writes with the
-- service-role key, which bypasses RLS.
